apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-kv-store
spec:
  provider:
    azurekv:
      tenantId: 1a27bdbf-e6cc-4e33-85d2-e1c81bad930a
      vaultUrl: https://kyungse-key-vault.vault.azure.net/
      authSecretRef:
        clientId:
          name: azure-auth
          key: clientId
          namespace: application
        clientSecret:
          name: azure-auth
          key: clientSecret
          namespace: application
        tenantId:
          name: azure-auth
          key: tenantId
          namespace: application
