apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-azure-app
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-azure-app
  template:
    metadata:
      labels:
        app: fastapi-azure-app
    spec:
      containers:
      - name: fastapi
        image: kyungsek8sclusterregistry.azurecr.io/azure-fastapi-bot:d64ce55
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: azure-secret
