apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure-secret
  namespace: application
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: azure-secret
    creationPolicy: Owner
  data:
    - secretKey: AZURE_SUBSCRIPTION_ID
      remoteRef:
        key: azure-subscription-id
    - secretKey: AZURE_TENANT_ID
      remoteRef:
        key: azure-tenant-id
    - secretKey: AZURE_CLIENT_ID
      remoteRef:
        key: azure-client-id
    - secretKey: AZURE_CLIENT_SECRET
      remoteRef:
        key: azure-client-secret
