apiVersion: v1
kind: Service
metadata:
  name: fastapi-azure-app
  namespace: application
spec:
  selector:
    app: fastapi-azure-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
  